# Generated by Django 4.0.4 on 2022-06-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Category_name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='Question_text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='Quiz_name',
        ),
    ]
